### ISSUE TITLE
message during provisioning, "hostname: unknown host"

### ISSUE THREAD

**Issue by mmarseglia** [terrimonster/puppet-control#9]
Hi,

  When I 'vagrant up' I get the following output regarding hostname and basename commands.  Not sure if this is an error or just informational.

=> xagent1: puppet-enterprise-3.7.2-el-6-x86_64.tar.gz already present
==> xagent1: puppet-enterprise-3.7.2-el-6-x86_64 already present
==> xagent1: ========================================================================
==> xagent1:
==> xagent1: Puppet Enterprise v3.7.2 installer
==> xagent1:
==> xagent1: Puppet Enterprise documentation can be found at http://docs.puppetlabs.com/pe/3.7/
==> xagent1: ------------------------------------------------------------------------
==> xagent1:
==> xagent1: STEP 1: READ ANSWERS FROM FILE
==> xagent1:
==> xagent1: ## Reading answers from file: /vagrant/provision/pe/answers/agent.txt
==> xagent1: hostname: Unknown host
==> xagent1: basename:
==> xagent1: missing operand
==> xagent1: Try `basename --help' for more information.
==> xagent1: iptables: Setting chains to policy ACCEPT: filter
==> xagent1: [  OK  ]
==> xagent1: iptables: Flushing firewall rules:
==> xagent1: [  OK  ]
==> xagent1: iptables: Unloading modules:
==> xagent1: [  OK  ]

**Comment by ahaeber** [comment]
Me too. A quick search on this issue takes me to http://unix.stackexchange.com/questions/187781/puppet-enterprise-install-fails-basename-missing-operand where the answer is that some puppet dependency is missing. But I don't quite understand this since apparently the same config works for the Master.

**Comment by mmarseglia** [comment]
the install here is using an "answer file" and in that stackexchange article the user is simply running the installer.  the hostname command used in the "answer file" is different between the master and agent answer files.

agent.txt calls $(hostname -f).  master.txt never uses that, it uses $(hostname) and $(hostname -s).

i suspect it's because the VMs FQDN is not configured correctly. in CentOS you must set the FQDN in /etc/sysconfig/networking for hostname -f to work properly. https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s2-sysconfig-network.html

**Comment by terrimonster** [comment]
Resolved.
